on:
  push:
    branches:
      - newmaster2








jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "login to docker hub"
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.TOKEN }}
      - name: "bulding docker image"
        run: docker build -t ${{ secrets.USERNAME }}/myimage .
      - name: "pushing docker image"
        run: docker push ${{ secrets.USERNAME}}/myimage

